- name: "Install CSC 11.1 from web"
  hosts: atg.docker-network

  roles:
    - role: "lean_delivery.java"
      transport: "web"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-java/jdk-7u191-linux-x64.tar.gz"
    - role: "lean_delivery.jboss"
      transport: "web"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-commerce-suite/app-servers/jboss-eap-6.1.0.zip"
    - role: lean_delivery.atg_platform
      transport: "web"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-commerce-suite/commerce/ATG11.1/V46005-01.zip"
    - role: lean_delivery.atg_csc
      csc_version: "11.1"
      transport: "web"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-commerce-suite/commerce/CSC11.1/OCServiceCenter11.1.zip"

  vars:
    atg_version: "11.1"
    dynamo_root: "/opt/atg/ATG{{ atg_version }}"
