FROM centos:8

RUN echo Update the image with the latest packages && \
	yum update -y && \
	echo Install OpenSSH and sudo && \
	yum install -y openssh-clients openssh-server sudo && \
	yum clean all

RUN echo Install Ansible && \
	yum install -y epel-release && \
	yum install -y ansible python2-ndg_httpsclient python-pyasn1 pyOpenSSL python-urllib3 \
	  wget iputils git && \
	yum clean all
	
RUN echo "root:Ansible!" | chpasswd

ENV ANSIBLE_DIR /ansible
WORKDIR $ANSIBLE_DIR
COPY ansible.cfg inventory.ini requirements.yml $ANSIBLE_DIR/
RUN ansible-galaxy install -r requirements.yml
COPY *.yml $ANSIBLE_DIR/

CMD ["/bin/bash"]