# Install lean_delivery.jboss role from the Ansible Galaxy
- src: lean_delivery.jboss
# Install lean_delivery.java role from the Ansible Galaxy
- src: lean_delivery.java
# Install lean_delivery.atg_platform role from Ansible Galaxy
- src: lean_delivery.atg_platform
# Install lean_delivery.atg_platform_patching from Ansible Galaxy
- src: lean_delivery.atg_platform_patching
# Install lean_delivery/atg_csc from Ansible Galaxy
#- src: lean_delivery.atg_csc
